import type { Subject, FormulaCard } from '@/types';

export const SUBJECTS: Subject[] = ['Physics', 'Chemistry', 'Mathematics', 'Computer Science'];

export const EXAM_OPTIONS = [
  'Class 12 Boards',
  'JEE Main',
  'JEE Advanced',
  'NEET',
  'GATE CSE',
  'UPSC CSE',
  'Class 10 Boards',
  'BITSAT',
] as const;

export const DEFAULT_SYLLABUS: Record<Subject, string[]> = {
  'Physics': [
    'Kinematics',
    'Laws of Motion',
    'Work, Energy & Power',
    'Rotational Motion',
    'Gravitation',
    'Thermodynamics',
    'Oscillations & Waves',
    'Electrostatics',
    'Current Electricity',
    'Magnetism',
    'EM Induction',
    'Optics',
    'Modern Physics',
    'Semiconductors',
  'Practicals',
  'Revision',
  'Mock Tests',
    'Doubt Clearing',
    'Previous Year Papers',
    'Formula Sheet Prep',
  'Chapter Quizzes',
    'Lab Record',
  'Viva Practice',
    'Project Work',
  'Group Study',
    'Self Assessment',
    'Peer Teaching',
    'Online Course',
    'Reference Book',
    'Notes Compilation',
  ],
  'Chemistry': [
    'Atomic Structure',
    'Chemical Bonding',
    'States of Matter',
    'Thermodynamics',
    'Equilibrium',
    'Redox Reactions',
    'Hydrogen',
    's-Block Elements',
    'p-Block Elements',
    'd & f-Block Elements',
    'Coordination Compounds',
    'Organic Basics',
    'Hydrocarbons',
    'Alcohols & Phenols',
    'Aldehydes & Ketones',
    'Amines',
    'Biomolecules',
    'Polymers',
    'Chemistry in Everyday Life',
    'Practicals',
    'Revision',
    'Mock Tests',
    'Previous Year Papers',
    'Formula Sheet Prep',
    'Chapter Quizzes',
    'Lab Record',
    'Viva Practice',
    'Project Work',
    'Group Study',
    'Self Assessment',
  ],
  'Mathematics': [
    'Sets & Functions',
    'Trigonometry',
    'Complex Numbers',
    'Quadratic Equations',
    'Sequences & Series',
    'Permutations & Combinations',
    'Binomial Theorem',
    'Straight Lines',
    'Conic Sections',
    '3D Geometry',
    'Vectors',
    'Limits & Continuity',
    'Differentiation',
    'Application of Derivatives',
    'Integration',
    'Application of Integrals',
    'Differential Equations',
    'Probability',
    'Statistics',
    'Matrices',
    'Determinants',
    'Revision',
    'Mock Tests',
    'Previous Year Papers',
    'Formula Sheet Prep',
    'Chapter Quizzes',
    'Practice Problems',
    'Group Study',
    'Self Assessment',
    'Reference Book',
  ],
  'Computer Science': [
    'Programming Fundamentals',
    'Data Types & Variables',
    'Control Structures',
    'Functions & Recursion',
    'Arrays & Strings',
    'Pointers',
    'Structures & Unions',
    'Object Oriented Programming',
    'Inheritance & Polymorphism',
    'Templates & STL',
    'Linked Lists',
    'Stacks & Queues',
    'Trees & Graphs',
    'Sorting Algorithms',
    'Searching Algorithms',
    'Dynamic Programming',
    'Database Concepts',
    'SQL Basics',
    'DBMS Normalization',
    'Operating Systems',
    'Computer Networks',
    'Data Communication',
    'Cyber Security',
    'Web Development',
    'Software Engineering',
    'Revision',
    'Mock Tests',
    'Previous Year Papers',
    'Project Work',
    'Self Assessment',
  ],
};

export const FORMULAS: FormulaCard[] = [
  {
    id: 'f1',
    subject: 'Physics',
    title: 'Kinematic Equations',
    category: 'Mechanics',
    content: 'v = u + at\ns = ut + ½at²\nv² = u² + 2as\ns = ½(u + v)t',
  },
  {
    id: 'f2',
    subject: 'Physics',
    title: "Newton's Second Law",
    category: 'Mechanics',
    content: 'F = ma\nImpulse: J = FΔt = Δp\nMomentum: p = mv',
  },
  {
    id: 'f3',
    subject: 'Physics',
    title: 'Gravitational Force',
    category: 'Gravitation',
    content: 'F = G(m₁m₂)/r²\nG = 6.674 × 10⁻¹¹ N·m²/kg²\ng = GM/R²',
  },
  {
    id: 'f4',
    subject: 'Physics',
    title: 'Ohm\'s Law & Power',
    category: 'Electricity',
    content: 'V = IR\nP = VI = I²R = V²/R\nSeries: R = R₁ + R₂\nParallel: 1/R = 1/R₁ + 1/R₂',
  },
  {
    id: 'f5',
    subject: 'Physics',
    title: 'Lens Formula',
    category: 'Optics',
    content: '1/f = 1/v - 1/u\nm = v/u = h\'/h\nLensmaker: 1/f = (n-1)(1/R₁ - 1/R₂)',
  },
  {
    id: 'f6',
    subject: 'Physics',
    title: 'Photoelectric Effect',
    category: 'Modern Physics',
    content: 'E = hf = hc/λ\nK.E._max = hf - φ\nV₀ = (hf - φ)/e',
  },
  {
    id: 'f7',
    subject: 'Chemistry',
    title: 'Ideal Gas Equation',
    category: 'Physical Chemistry',
    content: 'PV = nRT\nR = 8.314 J/(mol·K)\nPV = (m/M)RT\nDensity: ρ = PM/RT',
  },
  {
    id: 'f8',
    subject: 'Chemistry',
    title: 'pH & pOH',
    category: 'Physical Chemistry',
    content: 'pH = -log[H⁺]\npOH = -log[OH⁻]\npH + pOH = 14 (at 25°C)\nKa × Kb = Kw = 10⁻¹⁴',
  },
  {
    id: 'f9',
    subject: 'Chemistry',
    title: 'Molarity & Molality',
    category: 'Physical Chemistry',
    content: 'Molarity = moles solute / L solution\nMolality = moles solute / kg solvent\nMole fraction: x_A = n_A / (n_A + n_B)',
  },
  {
    id: 'f10',
    subject: 'Chemistry',
    title: 'Nernst Equation',
    category: 'Electrochemistry',
    content: 'E = E° - (RT/nF)lnQ\nAt 25°C: E = E° - (0.0591/n)logQ\nΔG = -nFE',
  },
  {
    id: 'f11',
    subject: 'Chemistry',
    title: 'Rate Law & Order',
    category: 'Chemical Kinetics',
    content: 'Rate = k[A]^m[B]^n\nFirst order: t½ = 0.693/k\nArrhenius: k = Ae^(-Ea/RT)',
  },
  {
    id: 'f12',
    subject: 'Mathematics',
    title: 'Quadratic Formula',
    category: 'Algebra',
    content: 'ax² + bx + c = 0\nx = (-b ± √(b² - 4ac)) / 2a\nDiscriminant: D = b² - 4ac',
  },
  {
    id: 'f13',
    subject: 'Mathematics',
    title: 'Trigonometric Identities',
    category: 'Trigonometry',
    content: 'sin²θ + cos²θ = 1\n1 + tan²θ = sec²θ\n1 + cot²θ = csc²θ\nsin(A±B) = sinAcosB ± cosAsinB',
  },
  {
    id: 'f14',
    subject: 'Mathematics',
    title: 'Derivative Rules',
    category: 'Calculus',
    content: 'd/dx(xⁿ) = nx^(n-1)\nd/dx(sin x) = cos x\nd/dx(e^x) = e^x\nProduct: (uv)\' = u\'v + uv\'\nQuotient: (u/v)\' = (u\'v - uv\')/v²',
  },
  {
    id: 'f15',
    subject: 'Mathematics',
    title: 'Integration Formulas',
    category: 'Calculus',
    content: '∫xⁿ dx = x^(n+1)/(n+1) + C\n∫(1/x) dx = ln|x| + C\n∫e^x dx = e^x + C\n∫sin x dx = -cos x + C',
  },
  {
    id: 'f16',
    subject: 'Mathematics',
    title: 'Binomial Theorem',
    category: 'Algebra',
    content: '(a + b)ⁿ = Σ C(n,k) a^(n-k) b^k\nC(n,k) = n! / (k!(n-k)!)\nC(n,0) + C(n,1) + ... + C(n,n) = 2ⁿ',
  },
  {
    id: 'f17',
    subject: 'Computer Science',
    title: 'Big-O Complexity',
    category: 'Algorithms',
    content: 'Binary Search: O(log n)\nMerge Sort: O(n log n)\nQuick Sort: O(n log n) avg\nBubble Sort: O(n²)\nDFS/BFS: O(V + E)',
  },
  {
    id: 'f18',
    subject: 'Computer Science',
    title: 'SQL Joins',
    category: 'Database',
    content: 'INNER JOIN: matching rows\nLEFT JOIN: all left + matches\nRIGHT JOIN: all right + matches\nFULL JOIN: all from both\nSELECT * FROM A JOIN B ON A.id = B.id',
  },
  {
    id: 'f19',
    subject: 'Computer Science',
    title: 'Binary Conversions',
    category: 'Fundamentals',
    content: 'Decimal → Binary: divide by 2, read remainders\nBinary → Decimal: Σ dᵢ × 2ⁱ\nHex: 0-9, A-F (base 16)\n1 byte = 8 bits, 1 KB = 1024 bytes',
  },
  {
    id: 'f20',
    subject: 'Computer Science',
    title: 'Recursion Base Case',
    category: 'Programming',
    content: 'function fib(n):\n  if n <= 1: return n\n  return fib(n-1) + fib(n-2)\n\nAlways define base case first!',
  },
];
